base_url = "https://0xa-at.github.io/jku.community/"
build_search_index = false
title = "jku.community"
compile_sass = true

[markdown]

[extra]
socials = [
{ name = "github", url = "https://github.com/0xa-at/jku.community", icon = "github" },
]
menu = [
    { name = "/linz", url = "/linz", weight = 1 },
    { name = "/about", url = "/about", weight = 2 },
]

# See https://github.com/not-matthias/apollo
[extra.analytics]
enabled = true

[extra.analytics.umami]
website_id = "4d764d5e-6d26-4286-b72a-a31637f3cdd5"
