base_url = "https://0xa-at.github.io/jku.community"
build_search_index = false
title = "jku.community"
compile_sass = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

menu = [
    { name = "About us", url = "/about", weight = 1 }
]
